name: Test Issue Forms
description: testing issue forms template
title: "[Test] :"

body:
- type: markdown
  value: "## Welcome!"
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord.
